language: go

dist: focal
sudo: required

go: "1.16.5"

jobs:
  include:
    - arch: amd64
    - arch: arm64-graviton2
      virt: vm
      group: edge
    - arch: amd64
      name: "amd64-race"
      if: type != pull_request
      env:
        - RACE=1
        - BASE_IMAGE=quay.io/cilium/cilium-runtime:da2f9d7aa2c18676f41f9119b2c54d5783d4922f@sha256:6ff8171605af9490c4462c3cd5f03b9b7de2e65b4d580fa60860a126f4b6a65c
        - LOCKDEBUG=1
    - arch: arm64-graviton2
      name: "arm64-graviton2-race"
      if: type != pull_request
      env:
        - RACE=1
        - BASE_IMAGE=quay.io/cilium/cilium-runtime:da2f9d7aa2c18676f41f9119b2c54d5783d4922f@sha256:6ff8171605af9490c4462c3cd5f03b9b7de2e65b4d580fa60860a126f4b6a65c
        - LOCKDEBUG=1
      virt: vm
      group: edge

if: branch = master OR type = pull_request

addons:
  apt:
    packages:
      - kernel-package
      - gnupg
      - libelf-dev
      - libncurses5

before_install: ./.travis/prepare.sh

before_script:
  - export PATH=/usr/local/clang/bin:$PATH

script: ./.travis/build.sh

notifications:
  email: false
